name: Get GitHub Deployments
description: Get GitHub a list of deployments that have been created by im-open/create-github-deployment.

inputs:
  token:
    description: A token with `deployments:read` and `contents:read` to get the deployments and release reference data.
    required: true
  environment:
    description: The name of a GitHub environment the release was deployed to, i.e. [Dev\|QA\|Stage\|Demo\|UAT\|Prod]. It will be used to filter deployment objects.
    required: true
  entity:
    description: The entity that is deployed, i.e. "proj-app", "proj-infrastruction" or "proj-db"
    required: true
  instance:
    description: A freeform identifier to distinguish separately deployed instances of the entity in the same environment. Typical uses would be to name a slot and/or region, e.g "NA26", "NA26-slot1", "NA27-blue", "Primary", "Secondary", etc.
    required: true

runs:
  using: node20
  main: dist/index.js
